name: pre-commit
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python environment
        uses: ./.github/actions/setup-env

      #      - name: Ensure uv pip is installed
      #        run: |
      #          uv pip install --upgrade pip

      # Create an alias to link 'pip' to 'uv pip'
      - name: Link pip to uv pip
        run: |
          echo 'alias pip="uv pip"' >> $GITHUB_ENV

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
